"""auto upgrade

Revision ID: 7954258644a2
Revises: cd5674015311
Create Date: 2026-05-29 20:55:45.090963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7954258644a2'
down_revision = 'cd5674015311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coupon', sa.Numeric(precision=18, scale=4), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('coupon')

    # ### end Alembic commands ###
