"""auto upgrade

Revision ID: cd5674015311
Revises: e0ab37295405
Create Date: 2026-05-29 19:26:15.319618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5674015311'
down_revision = 'e0ab37295405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('last_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coupon', sa.Numeric(precision=18, scale=4), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('last_price', schema=None) as batch_op:
        batch_op.drop_column('coupon')

    # ### end Alembic commands ###
